name: PR Title Checker

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ "main" ]


jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    
    steps:
      - name: Check PR base branch
        run: |
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Checking PR with base branch 'main'"
      
      - name: Read and print PR title
        run: |
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "PR Title check completed successfully"
